services:
  template-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: [
      3001:3001
    ]
    volumes:
      - ./backend/:/usr/src/template-backend
    environment:
      MONGO_URL: "${MONGO_URL}"
    depends_on:
      - template-mongo
    container_name: template-backend
  template-mongo:
    image: mongo:4.4.17
    ports: [
      3456:27017
    ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db
    container_name: template-mongo
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - template-frontend
      - template-backend
    container_name: template-nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: template-certbot
  template-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: /api
    ports: [
      5000:80
    ]
    volumes:
      - ./frontend/:/usr/src/template-frontend
    environment:
      REACT_APP_BACKEND_URL: /api
    tty: true
    container_name: template-frontend
volumes:
  mongo_data: